package com.whatsapp.clone.widgets.settingPrivacyLastSeen.ui.utils;

public enum LastSeenItem {
    EVERYONE, MY_CONTACT, MY_CONTACT_EXCEPT, NOBODY, ONLY_SHARE_WITH, HOURS, DAY, DAYS, OFF, SYSTEM_DEFAULT, LIGHT, DARK, SMALL, MEDIUM, LARGE,PHONES_LANGUAGE,
    LANGUAGE_ONE, LANGUAGE_TWO, LANGUAGE_THREE,LANGUAGE_FOUR, LANGUAGE_FIVE, LANGUAGE_SIX, LANGUAGE_SEVEN, LANGUAGE_EIGHT, LANGUAGE_NINE, LANGUAGE_TEN,
    AUTO,BEST_QUALITY,DATA_SAVER,DEFAULT,SHORT,LONG,NONE,WHITE,RED,YELLOW,GREEN,CYAN,BLUE,PURPLE
}