package com.whatsapp.clone.widgets.settingPrivacy.ui.utils;

public enum PrivacyItem {
    LAST_SEEN, PROFILE_PHOTO, ABOUT, STATUS, GROUPS, LIVE_LOCATION, BLOCKED_CONTACTS, FINGERPRINT_LOCK, FONT_SIZE, BACKUP_GOOGLE, GOOGLE_ACCOUNT,
    NOTIFICATION_TONE_MESSAGE, VIBRATE_MESSAGE, LIGHT_MESSAGE, NOTIFICATION_TONE_GROUP, VIBRATE_GROUP, LIGHT_GROUP, RINGTONE_CALL, VIBRATE_CALL,
    USING_MOBILE_DATA, CONNECTED_ON_WIFI, ROAMING, UPLOAD_QUALITY
}