package com.whatsapp.clone.widgets.accountItemView.ui.utils;

public enum AccountItem {
    PRIVACY, SECURITY, TWO_STEP_VERIFICATION, CHANGE_NUMBER, REQUEST_ACCOUNT_INFO, DELETE_MY_ACCOUNT, REQUEST_REPORT,EXPORT_CHAT,
    ARCHIVED_ALL_CHAT, CLEAR_ALL_CHATS, DELETE_ALL_CHATS, HELP_CENTRE, POLICY, APP_INFO
}
